name: Build and Release SDKs

# Trigger the workflow when pushing tags that match the pattern "v*"
on:
  push:
    tags:
      - "v*"

# Set the global GitHub token environment variable
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    name: Compile and Package SDKs
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Synchronize and update submodules recursively
      - name: Update submodules
        run: |
          git submodule sync --recursive  # Ensure submodule paths are up-to-date
          git submodule update --init --recursive  # Initialize and update all submodules

      # Step 3: Build projects using Docker Compose
      - name: Build SDKs with Docker Compose
        run: docker-compose up

      # Step 4: Zip each SDK directory
      - name: Zip SDK Files
        run: |
          zip -r inspireface-linux-armv7-armhf.zip build/inspireface-linux-armv7-armhf/
          zip -r inspireface-linux-armv7-rv1109rv1126-armhf.zip build/inspireface-linux-armv7-rv1109rv1126-armhf/
          zip -r inspireface-x86-linux-ubuntu18.zip build/inspireface-x86-linux-ubuntu18/

      # Step 5: Upload the zipped SDK files for the next job
      - name: Upload SDK Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sdk_files
          path: |
            inspireface-linux-armv7-armhf.zip
            inspireface-linux-armv7-rv1109rv1126-armhf.zip
            inspireface-x86-linux-ubuntu18.zip

  release:
    name: Release SDKs to GitHub
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository again
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Download the previously uploaded SDK files
      - name: Download SDK Artifacts
        uses: actions/download-artifact@v2
        with:
          name: sdk_files

      # Step 3: Create a GitHub Release and upload the SDK files
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            inspireface-linux-armv7-armhf.zip
            inspireface-linux-armv7-rv1109rv1126-armhf.zip
            inspireface-x86-linux-ubuntu18.zip
