name: Validate Apple coreml SDKs

on:
  push:
    branches: ["feature/coreml"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/apple-sdk.yaml
    with:
      backend: coreml
