name: Validate Apple cpu SDKs

on:
  push:
    branches: ["feature/build_ios"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/apple-sdk.yaml
    with:
      backend: cpu
