name: Build iOS CoreML Arm64

on:
  push:
    branches: ["feature/coreml"]

# Set the global GitHub token environment variable
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    name: Compile iOS-arm64
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Synchronize and update submodules recursively
      - name: Update submodules
        run: |
          git clone --recurse-submodules https://github.com/tunmx/inspireface-3rdparty.git 3rdparty

      # Step 3: Start building the SDK
      - name: Start Building the InspireFace-iOS
        run: |
          bash command/build_ios_coreml.sh
          ls build

      # Step 4: Upload the zipped SDK files for the next job
      - name: Upload SDK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk_files_ios_coreml_arm64
          path: |
            build/inspireface-ios-coreml-arm64.zip

      # Step 5: Zip SDK directory
      - name: Zip SDK directory
        run: |
          cd build
          zip -r ../inspireface-ios-coreml-arm64.zip inspireface-ios-coreml-arm64
          cd ..
          stat inspireface-ios-coreml-arm64.zip

      # Step 7: Upload the zipped SDK files for the next job
      - name: Upload SDK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk_files_ios_coreml_arm64
          path: |
            inspireface-ios-coreml-arm64.zip