name: Build Linux-Ubuntu-x86

# Trigger the workflow when pushing tags that match the pattern "v*"
#on:
#  push:
#    tags:
#      - "v*"

#on:
#  push:
#    branches: ["master"]
#  pull_request:
#    branches: ["master"]

on:
  push:
    branches: ["feature/aarch64"]

# Set the global GitHub token environment variable
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    name: Compile and Package SDKs
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Synchronize and update submodules recursively
      - name: Update submodules
        run: |
          git submodule sync --recursive  # Ensure submodule paths are up-to-date
          git submodule update --init --recursive  # Initialize and update all submodules

      # Step 3: Extract the version number from the tag (e.g., "v1.2.3" becomes "1.2.3")
      - name: Extract Version Number
        id: extract_version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')" >> $GITHUB_ENV

      # Step 4: Install necessary dependencies for building the CMake project
      - name: Install Dependencies
        run: |
          sudo apt-get update  # Update package lists
          # Install build tools and required libraries for video processing
          sudo apt-get install -y build-essential libgtk-3-dev libavcodec-dev libavformat-dev libjpeg-dev libswscale-dev

      # Step 5: Start building the SDK
      - name: Start Building the InspireFace-Linux-x86
        run: |
          bash command/build_linux_ubuntu18.sh
          ls build