name: Build Linux-Ubuntu-x86

on:
  push:
    branches: ["feature/build_ios"]

# Set the global GitHub token environment variable
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    name: Compile iOS-arm64
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Synchronize and update submodules recursively
      - name: Update submodules
        run: |
          git clone --recurse-submodules https://github.com/tunmx/inspireface-3rdparty.git 3rdparty

      # Step 3: Start building the SDK
      - name: Start Building the InspireFace-iOS
        run: |
          bash command/build_ios.sh
          ls build
