name: Build Linux-Ubuntu-x86

on:
  push:
    branches: ["feature/noexecstack"]

# Set the global GitHub token environment variable
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    name: Compile manylinux2014-x86
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Synchronize and update submodules recursively
      - name: Update submodules
        run: |
          git clone --recurse-submodules https://github.com/tunmx/inspireface-3rdparty.git 3rdparty
      
      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Execute the docker-compose command
      - name: Execute Docker Compose
        run: |
          docker-compose up build-manylinux2014-x86

      # Step 5: Check GNU_STACK flag
      - name: Check GNU_STACK flag
        run: |
          readelf -lW lib/libInspireFace.so | grep GNU_STACK

      # Step 6: Zip SDK directory
      - name: Zip SDK directory
        run: |
          cd build
          zip -r ../inspireface-linux-x86-manylinux2014.zip inspireface-linux-x86-manylinux2014
          cd ..
          stat inspireface-linux-x86-manylinux2014.zip

      # Step 6: Upload the zipped SDK files for the next job
      - name: Upload SDK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk_files_manylinux2014_x86
          path: |
            inspireface-linux-x86-manylinux2014.zip