name: Build Linux-Ubuntu-x86

on:
  push:
    branches: ["feature/build_x86"]

# Set the global GitHub token environment variable
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    name: Compile Linux-x86
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Synchronize and update submodules recursively
      - name: Update submodules
        run: |
          git clone --recurse-submodules https://github.com/HyperInspire/3rdparty.git

      # Step 3: Install necessary dependencies for building the CMake project
      - name: Install Dependencies
        run: |
          sudo apt-get update  # Update package lists
          # Install build tools and required libraries for video processing
          sudo apt-get install -y build-essential libgtk-3-dev libavcodec-dev libavformat-dev libjpeg-dev libswscale-dev

      # Step 4: Start building the SDK
      - name: Start Building the InspireFace-Linux-x86
        run: |
          bash command/build_linux_ubuntu18.sh
          ls build
