name: Build Linux-Ubuntu-x86

on:
  push:
    branches: ["feature/macos_x86", "dev/next-gen"]

# Set the global GitHub token environment variable
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    name: Compile MacOS-x86
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Synchronize and update submodules recursively
      - name: Update submodules
        run: |
          git clone --recurse-submodules https://github.com/tunmx/inspireface-3rdparty.git 3rdparty

      # Step 3: Install necessary dependencies for building the CMake project
      - name: Install Dependencies
        run: |
          brew install cmake

      # Step 4: Start building the SDK
      - name: Start Building the InspireFace-MacOS-x86
        run: |
          bash command/build_linux_macos_x86.sh
          ls build
